 name: CI- HTML Validation
 on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 jobs:
 validate-html:
 runs-on: ubuntu-latest
 steps:-name: Checkout code
 uses: actions/checkout@v3-name: Validate HTML5
 uses: Cyb3r-Jak3/html5validator-action@v8
 with:
 root: ./ # Répertoire racine contenant index.html
